// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqky2t5zXwh0ncJERbusqBKIKfm5o2mA',
    appId: '1:26293531066:web:81ee3f01c70e7b0f84ad83',
    messagingSenderId: '26293531066',
    projectId: 'cook-it-project-dee30',
    authDomain: 'cook-it-project-dee30.firebaseapp.com',
    databaseURL: 'https://cook-it-project-dee30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cook-it-project-dee30.firebasestorage.app',
    measurementId: 'G-6R2SWP0ZFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCATIkpVwyhKbleFSflduQyk6tHBTxPPFc',
    appId: '1:26293531066:android:78178289ff02616a84ad83',
    messagingSenderId: '26293531066',
    projectId: 'cook-it-project-dee30',
    databaseURL: 'https://cook-it-project-dee30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cook-it-project-dee30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vjkVFgGxNO6UNtgATa6dfHwpcOCLgcU',
    appId: '1:26293531066:ios:7c0a78e1045b964884ad83',
    messagingSenderId: '26293531066',
    projectId: 'cook-it-project-dee30',
    databaseURL: 'https://cook-it-project-dee30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cook-it-project-dee30.firebasestorage.app',
    iosClientId: '26293531066-6ineug4m8alfetiffttbbmde7ihubnp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediapipe2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vjkVFgGxNO6UNtgATa6dfHwpcOCLgcU',
    appId: '1:26293531066:ios:7c0a78e1045b964884ad83',
    messagingSenderId: '26293531066',
    projectId: 'cook-it-project-dee30',
    databaseURL: 'https://cook-it-project-dee30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cook-it-project-dee30.firebasestorage.app',
    iosClientId: '26293531066-6ineug4m8alfetiffttbbmde7ihubnp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediapipe2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiqky2t5zXwh0ncJERbusqBKIKfm5o2mA',
    appId: '1:26293531066:web:e15b2d0e40f2936884ad83',
    messagingSenderId: '26293531066',
    projectId: 'cook-it-project-dee30',
    authDomain: 'cook-it-project-dee30.firebaseapp.com',
    databaseURL: 'https://cook-it-project-dee30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cook-it-project-dee30.firebasestorage.app',
    measurementId: 'G-RZZZZ1268B',
  );

}